#!/bin/sh
#SBATCH --partition=gpu
#SBATCH --gpus=a100:2
#SBATCH -N 1      # nodes requested
#SBATCH -n 1      # tasks requested
#SBATCH -c 4      # cores requested
#SBATCH --mem=8gb  # memory in Mb
#SBATCH -o outfile  # send stdout to outfile
#SBATCH -e errfile  # send stderr to errfile
#SBATCH -t 20:00:00  # time requested in hour:minute:second

echo wassup
nvidia-smi
module load cuda/11.4.3
export CUDA_VISIBLE_DEVICES=3,4
~/myblue/woz/cai-nlp/venv/bin/python T5.py --mode predict \
    --GPU 1 --slot_lang slottype --ckpt_path save/t5-41000 \
    # --only_domain escai
